### ISSUE TITLE
EDT Violation in list update

### ISSUE THREAD

**Issue by DmitriGoldring** [iandees/josm-notes#4] opened 2013-08-16 00:23 UTC
While I am unsure whether it is the same problem as this JOSM ticket (https://josm.openstreetmap.de/ticket/8955), there is definitely an issue when the results from the note query are being used to update the list.

```
at org.openstreetmap.josm.plugins.notes.gui.NotesDialog.update(NotesDialog.java:243)
at org.openstreetmap.josm.plugins.notes.NotesPlugin.updateGui(NotesPlugin.java:216)
at org.openstreetmap.josm.plugins.notes.NotesPlugin.updateData(NotesPlugin.java:183)
at org.openstreetmap.josm.plugins.notes.NotesPlugin$DownloadNotesTask.run(NotesPlugin.java:308)
at java.util.TimerThread.mainLoop(Timer.java:555)
at java.util.TimerThread.run(Timer.java:505)
```

**Comment by iandees** [comment] 2013-08-24 17:32
Looks like a dupe of #9.

**Closed as completed by iandees** 2013-08-24 17:32 UTC
